import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Vendors mermaid (pinned major) + linkedom as standalone esbuild bundles so the
// skill's build-time mermaid-syntax gate (skills/.../scripts/lib/validate.mjs)
// can run mermaid.parse() in a node child process with no node_modules, no
// network, and no runtime deps — matching the repo's vendored-static-file
// convention (vendor/marked.min.js.txt, vendor/inter/*.ttf).
//
// This is a MANUAL vendor step (like subset-cjk-font.py): run it once when
// bumping the pinned mermaid major. It uses `npx esbuild` so the repo itself
// stays esbuild-free. The generated bundles are committed.
//
//   node scripts/vendor-mermaid.mjs
//
// Outputs:
//   vendor/mermaid/mermaid.bundle.mjs   (~3.4MB, mermaid + all its deps bundled)
//   vendor/mermaid/linkedom.bundle.mjs  (~480KB, a DOM shim sufficient for parse)
//   vendor/mermaid/LICENSE              (mermaid MIT, linkedom ISC)
//
// Why linkedom not jsdom: jsdom bundles to ~6MB and pulls ~60 deps; linkedom
// is a no-dep DOM that satisfies mermaid's DOMPurify path (classDiagram needs
// it; a hand-rolled shim does not), at ~480KB.

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
// The bundles ship WITH the skill so the build-time gate runs offline wherever
// the skill is installed (npx skills add), not just in this repo.
const outDir = join(root, "skills/using-open-artifacts/vendor/mermaid");
mkdirSync(outDir, { recursive: true });

const MERMAID_MAJOR = 11;
// Use a temp install dir so the repo's own node_modules isn't polluted.
const tmpDir = join(root, ".vendor-tmp");
mkdirSync(tmpDir, { recursive: true });

function npmInstall(spec) {
  // spec may include a version ("mermaid@11"); the installed dir is just the name.
  const name = spec.split("@")[0];
  const res = spawnSync(
    "npm",
    [
      "install",
      "--prefix",
      tmpDir,
      "--no-save",
      "--no-audit",
      "--no-fund",
      spec,
    ],
    { stdio: "inherit" },
  );
  if (res.status !== 0) throw new Error(`npm install ${spec} failed`);
  return join(tmpDir, "node_modules", name);
}

function esbuild(entry, outfile, extra = []) {
  const res = spawnSync(
    "npx",
    [
      "--yes",
      "esbuild@0.23.1",
      entry,
      "--bundle",
      "--platform=node",
      "--format=esm",
      "--minify",
      `--outfile=${outfile}`,
      ...extra,
    ],
    { stdio: "inherit" },
  );
  if (res.status !== 0) throw new Error(`esbuild ${outfile} failed`);
}

const mermaidEntry = join(
  npmInstall(`mermaid@${MERMAID_MAJOR}`),
  "dist/mermaid.esm.mjs",
);
const mermaidBundle = join(outDir, "mermaid.bundle.mjs");
esbuild(mermaidEntry, mermaidBundle);

const linkedomEntry = join(npmInstall("linkedom"), "esm/index.js");
const linkedomBundle = join(outDir, "linkedom.bundle.mjs");
esbuild(linkedomEntry, linkedomBundle);

// LICENSE — both MIT/ISC, free for any use.
writeFileSync(
  join(outDir, "LICENSE"),
  `mermaid.bundle.mjs — mermaid v${MERMAID_MAJOR} (MIT, https://github.com/mermaid-js/mermaid)
  bundled with all runtime deps (MIT ISC Apache-2.0).
linkedom.bundle.mjs — linkedom (ISC, https://github.com/WebReflection/linkedom)
  bundled standalone.

These bundles are generated by scripts/vendor-mermaid.mjs and committed so
the skill's build-time mermaid-syntax gate runs offline with no node_modules.
`,
);

console.log(`vendored mermaid v${MERMAID_MAJOR} + linkedom into ${outDir}`);
