import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "vendor/marked.min.js.txt"), "utf8");
const versionMatch = source.match(/marked v([\d.]+)/);

const out = `// Generated by scripts/vendor-marked.mjs from vendor/marked.min.js.txt
// marked ${versionMatch ? `v${versionMatch[1]}` : "(unknown version)"} — MIT licensed, https://github.com/markedjs/marked
export const MARKED_SOURCE: string = ${JSON.stringify(source)};
`;

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/marked-source.ts"), out);
console.log(`wrote src/generated/marked-source.ts (${out.length} bytes)`);
