import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// The OG card is rasterized by resvg-wasm, which has no access to system
// fonts, so the fonts it draws with must be embedded in the Worker bundle.
// resvg cannot compile fonts at runtime the way the .wasm is statically
// imported, so the TTFs are base64-encoded into a TS module here (mirroring
// vendor-marked.mjs) and decoded once at module load. The vendored files are
// Inter, instanced to two weights and subset to Latin + punctuation.
const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const fonts = [
  { name: "INTER_REGULAR", file: "vendor/inter/inter-regular.ttf" },
  { name: "INTER_SEMIBOLD", file: "vendor/inter/inter-semibold.ttf" },
];

const consts = fonts
  .map(({ name, file }) => {
    const b64 = readFileSync(join(root, file)).toString("base64");
    return `export const ${name}_TTF_BASE64: string =\n  ${JSON.stringify(b64)};`;
  })
  .join("\n\n");

const out = `// Generated by scripts/vendor-fonts.mjs from vendor/inter/*.ttf
// Inter (SIL OFL 1.1, https://github.com/rsms/inter) instanced to a single
// weight each and subset to Latin + punctuation. See vendor/inter/OFL.txt.
${consts}
`;

mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/fonts.ts"), out);
console.log(`wrote src/generated/fonts.ts (${out.length} bytes)`);
