import { Hono } from "hono";
import type { AppContext } from "./api";
import {
  api,
  artifactUrl,
  ogImageUrl,
  parseVersionParam,
  storeFrom,
} from "./api";
import { fontFaceCss, materializeFont, parseSlug } from "./fonts";
import { brandHomepageForCoda0, isCoda0Host } from "./home";
import { renderOgCardPng } from "./og";
import {
  badVersionPage,
  generateNonce,
  notFoundPage,
  unlockShell,
  userContentHeaders,
  wrapDocument,
} from "./wrap";

const app = new Hono<AppContext>();

app.route("/api", api);

// The landing page ships as a neutral "Open Artifacts" static asset. The Worker
// runs first for "/" (wrangler.jsonc run_worker_first) so it can rebrand the
// asset to "coda0" in the HTML itself on the hosted host — for crawlers and
// no-JS visitors, not just after the client script. Every other deploy returns
// the asset untouched, so a self-hoster's page stays "Open Artifacts".
app.get("/", async (c) => {
  const asset = await c.env.ASSETS.fetch(c.req.raw);
  if (!isCoda0Host(new URL(c.req.url).hostname)) return asset;
  if (!(asset.headers.get("content-type") ?? "").includes("text/html"))
    return asset;
  return brandHomepageForCoda0(asset);
});

// Opt-in same-origin web-font surface (env flag OPEN_ARTIFACTS_WEB_FONTS="1").
// Artifacts name a Fontshare family by slug `<family>--<weight>[--italic]`;
// the Worker materializes the .woff2 from Fontshare into R2 and serves it
// same-origin so no third-party host appears in the artifact CSP. The `.css`
// shim emits a derived @font-face so authors only write one <link>. Off by
// default — a non-opt-in deploy 404s both routes, preserving the strict CSP.
const WEB_FONT_CACHE_HEADERS = {
  "cache-control": "public, max-age=31536000, immutable",
  "x-content-type-options": "nosniff",
} as const;

app.get("/fonts/:slug{[a-z0-9-]+\\.(?:woff2|css)}", async (c) => {
  if (c.env.OPEN_ARTIFACTS_WEB_FONTS !== "1") {
    return new Response("not found", { status: 404 });
  }
  const raw = c.req.param("slug") ?? "";
  if (raw.endsWith(".css")) {
    const slug = raw.slice(0, -".css".length);
    const css = fontFaceCss(slug);
    if (css === null) {
      return new Response("not found", { status: 404 });
    }
    return new Response(css, {
      headers: {
        "content-type": "text/css; charset=utf-8",
        ...WEB_FONT_CACHE_HEADERS,
      },
    });
  }
  const slug = raw.slice(0, -".woff2".length);
  if (parseSlug(slug) === null) {
    return new Response("not found", { status: 404 });
  }
  const bytes = await materializeFont(slug, c.env);
  if (bytes === null) {
    return new Response("not found", { status: 404 });
  }
  return new Response(bytes, {
    headers: {
      "content-type": "font/woff2",
      ...WEB_FONT_CACHE_HEADERS,
    },
  });
});

// Self-hosted runtime-library bundle. The vendored mermaid IIFE bundle lives in
// public/vendor/mermaid.runtime.js (regenerated by scripts/vendor-mermaid.mjs,
// which appends a side-effect line so `window.mermaid` is set synchronously on
// load). It is loaded as a REGULAR (non-module) `<script src>` so the parser
// executes it synchronously (blocking) BEFORE the scripts-slot inline init runs
// — module scripts are deferred and would define `window.mermaid` only after
// the init guard had already run (the load-order bug, issue #11). Serving it
// same-origin — under script-src 'self' — lets mermaid load with NO external
// script host in the CSP, so the jsdelivr bypass (an artifact's inline JS
// createElement("script", {src: <external>}) to load an arbitrary package) is
// closed. The Worker re-serves the static asset with an explicit JavaScript
// MIME + nosniff so the regular <script src> always loads with the right type,
// regardless of how the assets runtime types .js. Unlike /fonts, this is not
// opt-in: mermaid is a build-time-allowlisted library, so the bundle ships on
// every deploy and the route always serves it.
app.get("/vendor/mermaid.runtime.js", async (c) => {
  const asset = await c.env.ASSETS.fetch(
    new Request(`${new URL(c.req.url).origin}/vendor/mermaid.runtime.js`),
  );
  if (!asset.ok) {
    return new Response("not found", { status: 404 });
  }
  return new Response(asset.body, {
    headers: {
      "content-type": "text/javascript; charset=utf-8",
      "cache-control": "public, max-age=31536000, immutable",
      "x-content-type-options": "nosniff",
    },
  });
});

app.get("/a/:id", async (c) => {
  const store = storeFrom(c);
  const record = await store.get(c.req.param("id"));
  const hostname = new URL(c.req.url).hostname;
  const webFonts = c.env.OPEN_ARTIFACTS_WEB_FONTS === "1";
  // One nonce per request: stamped on every viewer-injected inline <script> and
  // emitted in script-src so 'unsafe-inline' can be dropped (issue #11).
  const nonce = generateNonce();
  const htmlHeaders = (sandbox: boolean) =>
    userContentHeaders({
      sandbox,
      contentType: "text/html; charset=utf-8",
      webFonts,
      nonce,
    });

  if (record === null) {
    return new Response(notFoundPage(hostname), {
      status: 404,
      headers: htmlHeaders(true),
    });
  }

  const version = parseVersionParam(c.req.query("v"), record.currentVersion);
  if (typeof version !== "number") {
    const page =
      version.status === 400
        ? badVersionPage(hostname)
        : notFoundPage(hostname);
    return new Response(page, {
      status: version.status,
      headers: htmlHeaders(true),
    });
  }

  const content = await store.getContent(record.id, version);
  if (content === null) {
    return new Response(notFoundPage(hostname), {
      status: 404,
      headers: htmlHeaders(true),
    });
  }

  const url = artifactUrl(c, record.id);
  const ogImage = ogImageUrl(c, record.id);
  const brandUrl = c.env.BRAND_URL ?? null;

  if (content.encrypted !== null) {
    const page = unlockShell({
      title: record.title,
      description: record.description,
      favicon: record.favicon,
      format: record.format,
      url,
      ogImage,
      hostname,
      brandUrl,
      envelope: { ...content.encrypted, ciphertext: content.body },
      webFonts,
      nonce,
    });
    return new Response(page, { headers: htmlHeaders(false) });
  }

  const page = wrapDocument({
    title: record.title,
    description: record.description,
    favicon: record.favicon,
    format: record.format,
    content: content.body,
    url,
    ogImage,
    hostname,
    brandUrl,
    nonce,
  });
  return new Response(page, { headers: htmlHeaders(true) });
});

// OpenGraph card image: a 1200x630 PNG rasterized from a self-contained card
// built from the artifact's title + description. Social crawlers ignore SVG
// og:image, so this returns PNG. It is fetched independently of the artifact
// page (not bound by the page CSP) and makes no external requests itself.
app.get("/og/:id", async (c) => {
  const store = storeFrom(c);
  const record = await store.get(c.req.param("id"));
  if (record === null) {
    return new Response("not found", { status: 404 });
  }
  let png: Uint8Array;
  try {
    png = await renderOgCardPng({
      title: record.title,
      description: record.description,
      hostname: new URL(c.req.url).hostname,
    });
  } catch (error) {
    // A failed rasterization must not surface Hono's HTML error page to a
    // crawler expecting an image; return a plain error the requester can retry.
    console.error("og render failed", error);
    return new Response("og render failed", { status: 500 });
  }
  return new Response(png, {
    headers: {
      "content-type": "image/png",
      "cache-control": "public, max-age=300",
      "content-security-policy": "default-src 'none'",
      "x-content-type-options": "nosniff",
    },
  });
});

app.get("/health", (c) => c.json({ ok: true }));

export default app;
